"""Initial migration

Revision ID: 3b871402f234
Revises: 
Create Date: 2026-05-30 23:27:00.135544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b871402f234'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events_binned',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id_rotating', sa.String(length=128), nullable=False),
    sa.Column('tool_name', sa.String(length=50), nullable=False),
    sa.Column('intent_class', sa.String(length=50), nullable=True),
    sa.Column('amount_band', sa.String(length=50), nullable=True),
    sa.Column('purpose_band', sa.String(length=50), nullable=True),
    sa.Column('lender_type', sa.String(length=50), nullable=True),
    sa.Column('cost_band', sa.String(length=50), nullable=True),
    sa.Column('region_type', sa.String(length=50), nullable=True),
    sa.Column('event_month', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_binned_event_month'), 'analytics_events_binned', ['event_month'], unique=False)
    op.create_index(op.f('ix_analytics_events_binned_session_id_rotating'), 'analytics_events_binned', ['session_id_rotating'], unique=False)
    op.create_table('institutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_bn', sa.String(length=255), nullable=False),
    sa.Column('institution_type', sa.String(length=50), nullable=False),
    sa.Column('regulator', sa.String(length=100), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('phone_public', sa.String(length=50), nullable=True),
    sa.Column('is_islamic', sa.Boolean(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=True),
    sa.Column('raw_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_checklists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('product_category', sa.String(length=50), nullable=False),
    sa.Column('checklist_bn', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checklist_en', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('location_type', sa.String(length=50), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('upazila', sa.String(length=100), nullable=True),
    sa.Column('address_text', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('products_supported', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('phone_public', sa.String(length=50), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_bn', sa.String(length=255), nullable=False),
    sa.Column('description_short_bn', sa.Text(), nullable=True),
    sa.Column('min_amount', sa.Float(), nullable=True),
    sa.Column('max_amount', sa.Float(), nullable=True),
    sa.Column('min_tenor_months', sa.Integer(), nullable=True),
    sa.Column('max_tenor_months', sa.Integer(), nullable=True),
    sa.Column('islamic_flag', sa.Boolean(), nullable=False),
    sa.Column('official_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_fees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('fee_name', sa.String(length=255), nullable=False),
    sa.Column('fee_amount', sa.Float(), nullable=True),
    sa.Column('fee_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('rate_type', sa.String(length=50), nullable=False),
    sa.Column('nominal_rate', sa.Float(), nullable=False),
    sa.Column('effective_notes', sa.Text(), nullable=True),
    sa.Column('fee_notes', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('confidence_flag', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_rates')
    op.drop_table('product_fees')
    op.drop_table('products')
    op.drop_table('locations')
    op.drop_table('document_checklists')
    op.drop_table('source_records')
    op.drop_table('institutions')
    op.drop_index(op.f('ix_analytics_events_binned_session_id_rotating'), table_name='analytics_events_binned')
    op.drop_index(op.f('ix_analytics_events_binned_event_month'), table_name='analytics_events_binned')
    op.drop_table('analytics_events_binned')
    # ### end Alembic commands ###
